# Generated by Django 2.2.7 on 2019-12-13 19:54

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0008_auto_20191129_2234'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0003_auto_20191211_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('ID', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('code', models.TextField()),
                ('result', models.IntegerField(db_index=True, default=6)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('language', models.CharField(max_length=15)),
                ('time_cost', models.IntegerField(null=True)),
                ('memory_cost', models.IntegerField(null=True)),
                ('score', models.IntegerField(null=True)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'submission',
                'ordering': ('-create_time',),
            },
        ),
    ]
