# Generated by Django 2.2.7 on 2019-12-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
