# Generated by Django 2.2.7 on 2019-12-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='compile_error_info',
            field=models.TextField(null=True),
        ),
    ]
