# Generated by Django 2.2.7 on 2019-12-12 22:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20191204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'memory_cost': 0, 'results': [], 'score': 0, 'time_cost': 0}),
        ),
    ]
