# Generated by Django 2.2.7 on 2019-12-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_compile_error_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='shared',
            field=models.BooleanField(default=False),
        ),
    ]
