# Generated by Django 2.2.7 on 2019-12-13 09:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import submission.models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20191212_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submission',
            name='statistic_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=submission.models.default_statistic_info),
        ),
    ]
