# Generated by Django 2.2.7 on 2019-12-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0004_auto_20191213_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='statistic_info',
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time_cost',
            field=models.IntegerField(null=True),
        ),
    ]
