# Generated by Django 2.2.7 on 2019-12-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20191211_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmcontestrank',
            options={'ordering': ('-accepted_number',)},
        ),
        migrations.AlterModelOptions(
            name='oicontestrank',
            options={'ordering': ('-total_score',)},
        ),
    ]
