# Generated by Django 2.2.7 on 2019-12-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20191215_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acmcontestrank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='oicontestrank',
            options={},
        ),
    ]
