# Generated by Django 2.2.7 on 2019-11-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20191120_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='contest',
            field=models.ManyToManyField(blank=True, to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, to='problem.ProblemTag'),
        ),
    ]
