# Generated by Django 2.2.7 on 2019-11-20 23:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0003_auto_20191120_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
