# Generated by Django 2.2.7 on 2019-11-29 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0006_auto_20191121_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemtag',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
