# Generated by Django 2.2.7 on 2019-12-16 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('contest', '0004_auto_20191215_2000'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('problem', '0008_auto_20191129_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Contest')),
                ('first_ac', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contest_problem',
            },
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ('-create_time',)},
        ),
        migrations.RemoveField(
            model_name='problem',
            name='contest',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ManyToManyField(blank=True, through='problem.ContestProblem', to='contest.Contest'), ),
        migrations.AddField(
            model_name='contestproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem.Problem'),
        ),
    ]
