# Generated by Django 2.2.7 on 2019-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20191215_2000'),
        ('problem', '0009_auto_20191216_2041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('problem', 'contest')},
        ),
    ]
