# Generated by Django 2.2.7 on 2019-12-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20191215_2000'),
        ('problem', '0010_auto_20191216_2143'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('name', 'contest'), ('problem', 'contest')},
        ),
    ]
