# Generated by Django 2.2.7 on 2019-12-20 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20191220_2229'),
        ('problem', '0011_auto_20191216_2232'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestproblem',
            unique_together={('problem', 'contest')},
        ),
        migrations.RemoveField(
            model_name='contestproblem',
            name='name',
        ),
    ]
