# Generated by Django 2.2.7 on 2019-11-20 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('register_time', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone_number', models.CharField(max_length=15, null=True, verbose_name='Phone number')),
                ('qq_number', models.CharField(max_length=13, null=True, verbose_name='QQ number')),
                ('github_username', models.CharField(max_length=50, null=True)),
                ('desc', models.CharField(max_length=50, null=True)),
                ('type', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='UserLoginData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('msg', models.TextField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac', models.IntegerField(default=0)),
                ('submit', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=1500)),
                ('ac_prob', models.TextField(default='', null=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
