# Generated by Django 2.2.7 on 2019-11-21 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20191121_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='register_time',
        ),
    ]
