# Generated by Django 2.2.7 on 2019-12-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20191215_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='ranking',
        ),
    ]
